# -*- coding: utf-8 -*-
"""Web_Crawler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quR8UCsmt2pc1Wb4sTrbI0cA-p9F2eEK
"""

!pip -q install requests beautifulsoup4 feedparser tldextract
!pip -q install sentence-transformers scikit-learn torch transformers
!pip -q install stix2

!fusermount -u /co7ntent/drive 2>/dev/null
!rm -rf /content/drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from google.colab import drive #run once
drive.mount('/content/drive', force_remount=True)

import os, shutil
src = "/content/incidents_latest.csv"
dst = "/content/drive/MyDrive/incidents_latest.csv"

os.makedirs("/content/drive/MyDrive", exist_ok=True)
shutil.copy2(src, dst)   # use copy2 to preserve timestamp
print("Copied to:", dst)

# Verify
!ls -lah /content/drive/MyDrive | head -n 50

import os, re, time, json, math, sqlite3, hashlib
from datetime import datetime
from urllib.parse import urlparse, urljoin

import requests, feedparser, tldextract
from urllib import robotparser
from bs4 import BeautifulSoup

# ----- Config (edit these) -----
USER_AGENT = "CTI-OSINT-RealtimeCrawler/1.0 (+contact@example.com)"
REQUEST_TIMEOUT = 12
SLEEP_BETWEEN_REQUESTS = 1.0        # politeness delay (seconds)
SCHEDULE_SECONDS = 600               # loop interval (10 minutes). For demo set to 60–120.

# Sources (add India/CERT-In sources if you have them)
RSS_FEEDS = [
    "https://feeds.feedburner.com/TheHackersNews",
    "https://www.bleepingcomputer.com/feed/",
    "https://securityaffairs.com/feed",
]
HTML_SEEDS = [
    "https://thehackernews.com/",
    "https://www.bleepingcomputer.com/",
    "https://securityaffairs.com/",
    "http://www.volexity.com",
    "http://www.seqrite.com",
    "http://strikeready.com",
    "http://hunt.io",
    "https://www.dsci.in/resource/content/india-cyber-threat-report-2025"
]

# Thresholds
RELEVANCE_THRESHOLD = 0.50      # SBERT relevance cutoff for “CTI-like”
ATTACK_THRESHOLD = 0.65         # Probability cutoff for “attack possible”

# SQLite path (uses Colab ephemeral storage)
DB_PATH = "/content/cti_realtime.sqlite"

# Ensure output folder exists
os.makedirs("/content", exist_ok=True)

def gnews_rss(query: str):
    # encodes Google News RSS for a query (India-specific)
    import urllib.parse as _up
    q = _up.quote(query)
    return f"https://news.google.com/rss/search?q={q}+when:7d&hl=en-IN&gl=IN&ceid=IN:en"

INDIA_RSS_EXTRAS = [
    gnews_rss("cyber attack India"),
    gnews_rss("ransomware India"),
    gnews_rss("data breach India"),
    gnews_rss("CERT-In advisory"),
    gnews_rss("UPI fraud cyber"),
    gnews_rss("Aadhaar data leak"),
    gnews_rss("power grid cyber attack India"),
    gnews_rss("banking cyber incident India"),
    gnews_rss("telecom cyber attack India"),
    gnews_rss("railways cyber attack"),
]

INDIA_HTML_SEEDS = [
    # Add high-signal Indian sources you’re allowed to crawl
    "https://www.cnnbusiness.in/technology/",   # example placeholders—replace with your known sources
    "https://www.thehindu.com/sci-tech/technology/",
    "https://www.business-standard.com/technology",
    "https://www.livemint.com/technology/tech-news",
    "https://www.ndtv.com/business/tech",
    # Add sector CERTs / PSUs / govt advisories pages you have permission to crawl
    # e.g., sector regulators, public notices pages, vendor India blogs, etc.
]


# ---------------- India / CII Focused Sources ----------------

# Government CERTs / Cyber Authorities
INDIA_HTML_SEEDS += [
    "https://www.cert-in.org.in/",                    # National CERT
    "https://www.nciipc.gov.in/index1.html",          # NCIIPC Homepage
    "https://cybercrime.gov.in/",                     # MHA Cyber Crime Portal
    "https://www.meity.gov.in/",                      # Ministry of Electronics & IT
    "https://www.ncsc.gov.in/content/",               # National Cyber Security Coordinator
    "https://www.drdo.gov.in/drdo/",                  # DRDO — defense infra risks
]

# Sector Regulators for CIIs
INDIA_HTML_SEEDS += [
    "https://www.rbi.org.in/",                       # BFSI regulator — advisories
    "https://www.sebi.gov.in/",                      # Securities regulator
    "https://www.irda.gov.in/",                      # Insurance regulator
    "https://www.trai.gov.in/",                      # Telecom regulator
    "https://powermin.gov.in/en",                    # Power sector — cyber notices possible
    "https://www.aai.aero/en/media-centre/news",     # Airport Authority (Transport)
    "https://www.indianrailways.gov.in/",            # Indian Railways
    "https://www.nhai.gov.in/#/media",               # National Highways Authority
    "https://www.mohfw.gov.in/",                     # Health Ministry (Hospitals infra)
]

# Indian PSUs / CII Operators
INDIA_HTML_SEEDS += [
    "https://www.ntpc.co.in/en/media/press-releases",
    "https://www.powergridindia.com/en/press-release",
    "https://www.ongcindia.com/news",
    "https://iocl.com/news",
    "https://www.gailonline.com/EN/press-releases",
    "https://eventussecurity.com/cybersecurity/india/cyber-attacks/",
    "https://www.bharatpetroleum.in/media/news/",
    "https://www.hindustanpetroleum.com/documents",
]

# Indian Cybersecurity Reports & News
INDIA_HTML_SEEDS += [
    "https://www.securityphd.in/",                   # cyber intel blog (India-heavy)
    "https://www.bankinfosecurity.com/asia",         # APAC banking cybersecurity
    "https://www.itvarnews.com/category/security/",  # IT security + gov press
    "https://inc42.com/technology/cybersecurity/",   # Startups + BFSI breaches
    "https://timesofindia.indiatimes.com/topic/cyber-security",
    "https://www.livemint.com/technology/tech-news",
    "https://www.thehindu.com/sci-tech/technology/",
    "https://www.business-standard.com/technology"
]

# Indian News RSS via Google News Queries (auto-updating)
INDIA_RSS_EXTRA2 = [
    gnews_rss("Indian power grid cyber"),
    gnews_rss("cert in advisory cybersecurity"),
    gnews_rss("ministry of defence cyber security"),
    gnews_rss("telecom data breach India"),
    gnews_rss("railways cyber attack India"),
    gnews_rss("Aadhaar breach cyber"),
    gnews_rss("UPI cyber fraud"),
    gnews_rss("critical infrastructure cyber India")
]
# INDIA_RSS_EXTRAS = [ ... ]

# ADD THESE
CERT_IN_FEEDS = [
    "https://www.cert-in.org.in/s2c/rss/Advisories.xml",
    "https://www.cert-in.org.in/s2c/rss/Vulnerabilities.xml",
    "https://www.cert-in.org.in/s2c/rss/PressRelease.xml"
]

# ADD MORE INDIAN CTI BLOGS
INDIAN_CTI_BLOGS = [
    "https://cyraacs.com/feed/",
    "https://cyberops.in/blog/feed/",
    "https://seqrite.com/blog/feed/",
    "https://kratikal.com/blog/feed/",
    "https://gbhackers.com/feed/",
    "https://cybersecurityhive.com/feed/"
]
# ...
# [Near the end of the cell]
# ...
RSS_FEEDS = list(dict.fromkeys(RSS_FEEDS + INDIA_RSS_EXTRA2 + INDIA_RSS_EXTRAS + CERT_IN_FEEDS + INDIAN_CTI_BLOGS))
HTML_SEEDS = list(dict.fromkeys(HTML_SEEDS + INDIA_HTML_SEEDS))

print("Total India + Global RSS:", len(RSS_FEEDS))
print("Total India + Global HTML:", len(HTML_SEEDS))

# --- DB

def get_conn(path=DB_PATH):
    return sqlite3.connect(path, check_same_thread=False)

def init_db(conn):
    cur = conn.cursor()
    # MODIFICATION: Added attack_type TEXT
    cur.execute("""CREATE TABLE IF NOT EXISTS incidents(
        id TEXT PRIMARY KEY,
        ts TEXT,
        source TEXT,
        url TEXT,
        title TEXT,
        text TEXT,
        relevance_score REAL,
        attack_prob REAL,
        attack_label INTEGER,
        attack_type TEXT,
        iocs_json TEXT,
        domain TEXT
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS seen_urls(
        url TEXT PRIMARY KEY,
        content_sha TEXT,
        first_seen TEXT,
        last_seen TEXT
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS frontier(
        url TEXT PRIMARY KEY,
        domain TEXT,
        priority REAL,
        added_ts TEXT,
        last_tried TEXT
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS domains(
        domain TEXT PRIMARY KEY,
        trials INTEGER,
        reward_sum REAL,
        last_update TEXT
    )""")
    conn.commit()

# --- MODIFICATION: This function is now fixed ---
def upsert_incident(conn, rid, rec):
    cur = conn.cursor()
    # FIX 1: Added 'attack_type' to the column list
    # FIX 2: Added the 12th '?' to the VALUES list
    cur.execute("""INSERT OR REPLACE INTO incidents
        (id, ts, source, url, title, text, relevance_score, attack_prob, attack_label, attack_type, iocs_json, domain)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?)""", (
            rid,
            rec.get("ts") or datetime.utcnow().isoformat(),
            rec.get("source",""),
            rec.get("url",""),
            rec.get("title",""),
            rec.get("text",""),
            float(rec.get("relevance_score", 0.0)),
            float(rec.get("attack_prob", 0.0)),
            int(rec.get("attack_label", 0)),
            rec.get("attack_type", "Other"), # <-- This is the 10th value
            json.dumps(rec.get("iocs") or {}), # <-- This is the 11th value
            rec.get("domain","") # <-- This is the 12th value
        )
    )
    conn.commit()

# --- (Rest of the functions are unchanged) ---
def get_seen_sha(conn, url):
    cur = conn.cursor()
    row = cur.execute("SELECT content_sha FROM seen_urls WHERE url=?", (url,)).fetchone()
    return row[0] if row else None

def upsert_seen(conn, url, content_sha):
    now = datetime.utcnow().isoformat()
    cur = conn.cursor()
    if get_seen_sha(conn, url) is None:
        cur.execute("INSERT INTO seen_urls(url, content_sha, first_seen, last_seen) VALUES(?,?,?,?)",
                    (url, content_sha, now, now))
    else:
        cur.execute("UPDATE seen_urls SET content_sha=?, last_seen=? WHERE url=?",
                    (content_sha, now, url))
    conn.commit()

def push_frontier(conn, url, domain, priority):
    cur = conn.cursor()
    cur.execute("""INSERT OR REPLACE INTO frontier(url, domain, priority, added_ts, last_tried)
                   VALUES(?,?,?,?,?)""",
                (url, domain, float(priority), datetime.utcnow().isoformat(), None))
    conn.commit()

def pop_frontier_batch(conn, n=100):
    cur = conn.cursor()
    rows = cur.execute("SELECT url, domain FROM frontier ORDER BY priority DESC LIMIT ?", (n,)).fetchall()
    for url, _ in rows:
        cur.execute("UPDATE frontier SET last_tried=? WHERE url=?", (datetime.utcnow().isoformat(), url))
    conn.commit()
    return rows

def delete_from_frontier(conn, url):
    cur = conn.cursor()
    cur.execute("DELETE FROM frontier WHERE url=?", (url,))
    conn.commit()

def get_domain_stats(conn, domain):
    cur = conn.cursor()
    row = cur.execute("SELECT trials, reward_sum FROM domains WHERE domain=?", (domain,)).fetchone()
    if row: return {"trials": row[0], "reward_sum": row[1]}
    return {"trials": 0, "reward_sum": 0.0}

def update_domain_reward(conn, domain, reward):
    cur = conn.cursor()
    stats = get_domain_stats(conn, domain)
    trials = stats["trials"] + 1
    reward_sum = stats["reward_sum"] + float(reward)
    cur.execute("""INSERT OR REPLACE INTO domains(domain, trials, reward_sum, last_update)
                   VALUES(?,?,?,?)""",
                (domain, trials, reward_sum, datetime.utcnow().isoformat()))
    conn.commit()

import re
import hashlib
from datetime import datetime
from urllib.parse import urlparse, urljoin
import requests
import tldextract
from urllib import robotparser
from bs4 import BeautifulSoup

_robot_cache = {}

def sha256(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8","ignore")).hexdigest()

def domain_from(url: str) -> str:
    try:
        return urlparse(url).netloc.lower()
    except Exception:
        return ""

def allowed_by_robots(url: str, ua: str = USER_AGENT) -> bool:
    base = f"{urlparse(url).scheme}://{urlparse(url).netloc}"
    if base not in _robot_cache:
        rp = robotparser.RobotFileParser()
        rp.set_url(urljoin(base, "/robots.txt"))
        try: rp.read()
        except Exception:
            _robot_cache[base] = None
            return True
        _robot_cache[base] = rp
    rp = _robot_cache[base]
    return True if rp is None else rp.can_fetch(ua, url)

def http_get(url: str, headers=None, timeout=REQUEST_TIMEOUT):
    if not allowed_by_robots(url):
        return None
    h = {"User-Agent": USER_AGENT}
    if headers: h.update(headers)
    try:
        r = requests.get(url, headers=h, timeout=timeout)
        if r.status_code == 200 and "text/html" in r.headers.get("Content-Type",""):
            return r
    except Exception:
        return None
    return None
BLACKLIST_PATTERNS = re.compile (
    r"/(sports|entertainment|movies|lifestyle|fashion|horoscope|videos|gallery)/",
    re.
    )

def extract_links(base_url: str, html: str, max_links=25):

    soup = BeautifulSoup(html, "html.parser")
    link_list = []
    for a in soup.find_all("a", href=True):
        href = a["href"].strip()
        if href.startswith("//"): href = "https:" + href
        if href.startswith("/"): href = urljoin(base_url, href)
        if href.startswith("http"):
            link_list.append(href)
    root = tldextract.extract(base_url)
    d = f"{root.domain}.{root.suffix}"
    pruned = []
    for u in link_list:
        if d in urlparse(u).netloc or re.search(r"/(news|story|article|advisory|blog)/", u, re.I):
            pruned.append(u)
    out, seen = [], set()
    for u in pruned:
        if u not in seen:
            seen.add(u); out.append(u)
    return out[:max_links]

#crawler utility
import re
import hashlib
from datetime import datetime
from urllib.parse import urlparse, urljoin
import requests
import tldextract
from urllib import robotparser
from bs4 import BeautifulSoup

_robot_cache = {}

def sha256(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8","ignore")).hexdigest()

def domain_from(url: str) -> str:
    try:
        return urlparse(url).netloc.lower()
    except Exception:
        return ""

def allowed_by_robots(url: str, ua: str = USER_AGENT) -> bool:
    base = f"{urlparse(url).scheme}://{urlparse(url).netloc}"
    if base not in _robot_cache:
        rp = robotparser.RobotFileParser()
        rp.set_url(urljoin(base, "/robots.txt"))
        try: rp.read()
        except Exception:
            _robot_cache[base] = None
            return True
        _robot_cache[base] = rp
    rp = _robot_cache[base]
    return True if rp is None else rp.can_fetch(ua, url)

def http_get(url: str, headers=None, timeout=REQUEST_TIMEOUT):
    if not allowed_by_robots(url):
        return None
    h = {"User-Agent": USER_AGENT}
    if headers: h.update(headers)
    try:
        r = requests.get(url, headers=h, timeout=timeout)
        if r.status_code == 200 and "text/html" in r.headers.get("Content-Type",""):
            return r
    except Exception:
        return None
    return None

# --- FIX 1: Corrected the regex definition ---
BLACKLIST_PATTERNS = re.compile(
    r"/(sports|entertainment|movies|lifestyle|fashion|horoscope|videos|gallery)/",
    re.I  # <-- This was the syntax error
)

def extract_links(base_url: str, html: str, max_links=25):

    soup = BeautifulSoup(html, "html.parser")
    link_list = []
    for a in soup.find_all("a", href=True):
        href = a["href"].strip()

        # --- FIX 2: Added logic to USE the blacklist ---
        if BLACKLIST_PATTERNS.search(href):
            continue
        # --- End of FIX 2 ---

        if href.startswith("//"): href = "https:" + href
        if href.startswith("/"): href = urljoin(base_url, href)
        if href.startswith("http"):
            link_list.append(href)

    root = tldextract.extract(base_url)
    d = f"{root.domain}.{root.suffix}"
    pruned = []
    for u in link_list:
        if d in urlparse(u).netloc or re.search(r"/(news|story|article|advisory|blog)/", u, re.I):

            # --- FIX 3: Added a second blacklist check for safety ---
            if not BLACKLIST_PATTERNS.search(u):
                pruned.append(u)
            # --- End of FIX 3 ---

    out, seen = [], set()
    for u in pruned:
        if u not in seen:
            seen.add(u); out.append(u)
    return out[:max_links]

#text processing
IOC_PATTERNS = {
    "ipv4": re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"),
    "domain": re.compile(r"\b(?:(?!-)[A-Za-z0-9-]{1,63}(?<!-)\.)+(?:[A-Za-z]{2,63})\b"),
    "url": re.compile(r"\bhttps?://[^\s<>'\"()]+", re.I),
    "sha256": re.compile(r"\b[a-fA-F0-9]{64}\b"),
    "md5": re.compile(r"\b[a-fA-F0-9]{32}\b"),
    "cve": re.compile(r"\bCVE-\d{4}-\d{4,7}\b", re.I),
}

def deobfuscate(text: str) -> str:
    t = re.sub(r"hxxp", "http", text, flags=re.I)
    t = t.replace("[.]", ".").replace("(.)", ".")
    t = re.sub(r"\s+\.\s+", ".", t)
    return t

def clean_text(title: str, body: str) -> str:
    t = f"{title or ''}. {body or ''}".strip()
    t = re.sub(r"\s+", " ", t)
    return deobfuscate(t)

def extract_iocs(text: str) -> dict:
    t = deobfuscate(text)
    out = {}
    for k, rx in IOC_PATTERNS.items():
        out[k] = list(set(rx.findall(t)))[:50]
    return out

#data collection module
def poll_rss(feed_url: str):
    items = []
    if not allowed_by_robots(feed_url):
        return items
    fp = feedparser.parse(feed_url)
    for e in fp.entries[:50]:
        url = getattr(e, "link", None)
        title = getattr(e, "title", "") or ""
        body  = ""
        if hasattr(e, "summary"):
            body = BeautifulSoup(e.summary, "html.parser").get_text(" ", strip=True)
        elif hasattr(e, "content") and e.content:
            body = BeautifulSoup(e.content[0].value, "html.parser").get_text(" ", strip=True)
        published = getattr(e, "published", "") or ""
        items.append({
            "url": url, "title": title, "body": body, "published": published,
            "source": "rss", "seed": feed_url
        })
    return items

def fetch_article(url: str):
    r = http_get(url)
    if not r:
        return {"url": url, "title": "", "body": ""}
    soup = BeautifulSoup(r.text, "html.parser")
    title = soup.title.string.strip() if soup.title and soup.title.string else ""
    paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
    body = " ".join(paragraphs)
    time.sleep(SLEEP_BETWEEN_REQUESTS)
    return {"url": url, "title": title, "body": body}

def crawl_html_seed(seed_url: str, per_seed: int = 25):
    out = []
    r = http_get(seed_url)
    if not r: return out
    for link in extract_links(seed_url, r.text, max_links=per_seed):
        art = fetch_article(link)
        if len((art["title"] + " " + art["body"]).strip()) >= 120:
            art.update({"source":"html", "seed": seed_url, "published": ""})
            out.append(art)
    return out

from sentence_transformers import SentenceTransformer
import numpy as np

# Load once (Colab will download the model the first time)
_sbert = SentenceTransformer("all-MiniLM-L6-v2")

def embed(text: str) -> np.ndarray:
    return _sbert.encode([text], normalize_embeddings=True, show_progress_bar=False)[0]

# Simple centroid approach for relevance (replace later with your trained classifier if you want)
_CTI_SEED_TERMS = [
    "ransomware attack on indian bank",
    "malware campaign targeting power grid",
    "phishing on UPI users in india",
    "data breach telecom india",
    "ddos attack on indian government portal",
    "critical infrastructure cyber incident india",
]
_centroid = np.mean(np.stack([embed(t) for t in _CTI_SEED_TERMS], axis=0), axis=0)

def relevance_score(text: str) -> float:
    if not text: return 0.0
    v = embed(text)
    cos = float(np.dot(v, _centroid))  # normalized → dot = cosine
    return max(0.0, min(1.0, (cos + 1.0)/2.0))

# Attack / not-attack heuristic (swap with DistilBERT later for better accuracy)
_ATTACK_HITS = re.compile(
    r"ransom|phish|smish|vish|malware|virus|infostealer|trojan|botnet|backdoor|keylogger|"
    r"ddos|denial\s+of\s+service|exploit|0-?day|rce|cve-\d{4}-\d{4,7}|breach|data\s+leak|exfiltrat",
    re.I
)

def attack_probability(text: str, iocs: dict | None = None) -> float:
    score = 0.0
    if _ATTACK_HITS.search(text): score += 0.6
    if iocs and any(iocs.get(k) for k in ("cve","url","ipv4","sha256","md5")): score += 0.3
    return min(score, 0.99)

# ---- India relevance signals ----
INDIA_CORE_TERMS = [
    "india","indian","bharat","hindustan","new delhi","mumbai","bangalore","bengaluru","chennai","hyderabad","gurugram","noida",
    "aadhaar","uidai","npci","upi","imps","aadhaar-enabled","fastag","digilocker","cowin",
    "cert-in","nciipc","nic","nic.in","gov.in","meity","rbi","sebi","irda","mha","mha.gov.in",
    "psu","public sector undertaking","sbi","pn b","bank of baroda","canara bank",
    "airtel","jio","vi","bsnl",
    "indian railways","railway","airport authority of india","aai","metro rail",
    "ntpc","power grid","ongc","gail","iocl","bpcl","hpcl",
    "isro","drdo","npcil","bhavini",
]
INDIAN_STATES_UT = [
    "andhra pradesh","arunachal pradesh","assam","bihar","chhattisgarh","goa","gujarat","haryana","himachal pradesh",
    "jharkhand","karnataka","kerala","madhya pradesh","maharashtra","manipur","meghalaya","mizoram","nagaland",
    "odisha","punjab","rajasthan","sikkim","tamil nadu","telangana","tripura","uttar pradesh","uttarakhand","west bengal",
    "andaman and nicobar","chandigarh","dadra and nagar haveli","daman and diu","delhi","jammu and kashmir","ladakh","lakshadweep","puducherry"
]

def india_relevance_score(text: str) -> float:
    if not text: return 0.0
    t = text.lower()
    score = 0.0

    # strong signals
    for kw in ["aadhaar","uidai","npci","upi","cert-in","nciipc","gov.in","nic.in","rbi","sebi","irda","isro","drdo","npcil"]:
        if kw in t: score += 0.25

    # broader India context + states
    hits_core = sum(1 for kw in INDIA_CORE_TERMS if kw in t)
    hits_states = sum(1 for s in INDIAN_STATES_UT if s in t)
    score += 0.03 * hits_core + 0.02 * hits_states

    # INR & TLD hints
    if "₹" in text or "inr" in t: score += 0.05
    if ".in" in t: score += 0.05

    return min(1.0, score)

# --- This is a NEW CELL (e.g., "Cell 10-B") ---
#
# Load ML libraries for attack type classification
#
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
import pandas as pd
import warnings

print("--- Training Attack Type Classifier ---")
warnings.filterwarnings("ignore") # Suppress sklearn warnings

# Global variable to hold our trained model
_attack_type_classifier = None

def train_attack_type_model():
    global _attack_type_classifier

    # --- IMPORTANT ---
    # Make sure your labeled CSV is uploaded to your Colab session
    csv_path = 'InteractiveSheet_2025-10-30_08_24_39 - Sheet1.csv'

    try:
        df_labeled = pd.read_csv(csv_path)
    except FileNotFoundError:
        print(f"ERROR: Labeled data file not found at {csv_path}")
        print("Please upload your CSV to train the attack type model.")
        return

    if 'text' not in df_labeled.columns or 'label_attack_type' not in df_labeled.columns:
        print("ERROR: CSV must have 'text' and 'label_attack_type' columns.")
        return

    print(f"Loaded {len(df_labeled)} labeled examples.")

    # Define our training pipeline
    # It automatically converts text to a TF-IDF matrix, then feeds it to a Linear Support Vector Classifier
    text_clf = Pipeline([
        ('tfidf', TfidfVectorizer(stop_words='english', max_df=0.9, min_df=2)),
        ('clf', LinearSVC(C=1.0, class_weight='balanced', random_state=42)),
    ])

    # Train the model
    text_clf.fit(df_labeled['text'], df_labeled['label_attack_type'])

    _attack_type_classifier = text_clf
    print("✅ Attack type classifier trained and ready.")
    print(f"Classes: {_attack_type_classifier.classes_}")

# --- Run the training function once ---
train_attack_type_model()

# --- Prediction function ---
def predict_attack_type(text: str) -> str:
    if not _attack_type_classifier:
        return "Unknown" # Model failed to train

    # Check if the article was already labeled as "not an attack"
    # This check is now handled by the attack_label logic in the main loop

    try:
        # The model expects a list of texts
        prediction = _attack_type_classifier.predict([text])
        return prediction[0]
    except Exception as e:
        print(f"Attack type prediction error: {e}")
        return "Error"

def compute_priority(parent_relevance: float, base: float = 0.1) -> float:
    # Boost children of relevant pages; keep a small base for exploration
    return base + max(0.0, parent_relevance)

def prepare_seed_frontier(conn, seed_urls):
    for u in seed_urls:
        push_frontier(conn, u, domain_from(u), priority=0.1)

def pick_urls(conn, n=100):
    return pop_frontier_batch(conn, n=n)

# ---------------- Improved Sector Tagging Dictionary (India CII Focus) ----------------
# Crawler Frontier Logic

CII_SECTOR_KEYWORDS = {
    "BFSI": [
        # Regulators & Schemes
        "rbi","sebi","irda","npci","asebi",
        "upi","imps","neft","rtgs","aadhaar-enabled","bbps","psp","payment aggregator",
        # Banks - PSU + Private Major Targets
        "sbi","state bank of india","hdfc bank","icici bank","axis bank","kotak",
        "bank of baroda","canara bank","punjab national bank","pnb",
        "idbi","idfc first bank","uco bank","union bank of india",
        "atm","credit card","debit card","fintech","wallet","nbfc"
    ],

    "Power & Energy": [
        "power grid","pgcil","ntpc",
        "adani power","jsw energy","tata power",
        "load dispatch","smart meter","grid substation","scada","transmission","distribution",
        "npcil","atomic power","thermal plant","coal plant",
        "renewable energy","hydro plant"
    ],

    "Telecom": [
        "airtel","reliance jio","jio","vi","vodafone idea","bsnl","mtnl",
        "4g","5g","telecom operator",
        "bts","msc","fiber cut","internet outage",
        "mobile tower"
    ],

    "Oil & Gas": [
        "ongc","iocl","bpcl","hpcl","gail",
        "oil india","petroleum","refinery","pipeline","gas leak","lng","lpg"
    ],

    "Transport": [
        # Railways & Metro
        "indian railways","irctc","railway station","metro rail","dmrc","kmrcl",
        # Aviation
        "airport authority of india","aai","air india","indigo","spicejet",
        # Roads & Ports
        "nhai","national highways authority of india","port trust","shipping corporation",
        "logistics company"
    ],

    "Government / Public": [
        "govt of india","government of india","ministry","secretariat","nic",
        "home ministry","mha","defence ministry","mod",
        "state government","municipal corporation","psu","public sector undertaking",
        "nciipc","cert-in","meity","drdo","isro","cyber police","parliament",
        "court","police","cbi"
    ],

    "Healthcare": [
        "hospital","clinic","health ministry","mohfw","ayushman bharat",
        "abha id","ehealth","cowin","nhm",
        "apollo","fortis","max hospital","aiims",
        "medical research centre"
    ],

    "Water & Environment": [
        "jal shakti","jal board","water supply","barrage","dam",
        "central pollution control board","cpcb"
    ],

    "Financial Market Infra": [
        "nsdl","cdsl","nse","bse",
        "stock exchange","depository"
    ]
}
import math

# Optional: mark some "strong" keywords for extra weight
_STRONG_HINTS = {
    "BFSI": {"rbi","sebi","irda","npci","upi","imps","neft","rtgs","bbps","payment aggregator",
             "state bank of india","sbi","hdfc bank","icici bank","axis bank","kotak"},
    "Power & Energy": {"pgcil","power grid","ntpc","scada","smart meter"},
    "Telecom": {"reliance jio","jio","airtel","vi","vodafone idea","bsnl","5g"},
    "Oil & Gas": {"ongc","iocl","bpcl","hpcl","gail","refinery","pipeline"},
    "Transport": {"indian railways","irctc","aai","airport authority of india","nhai","dmrc"},
    "Government / Public": {"nciipc","cert-in","nic","meity","mha","isro","drdo","psu"},
    "Healthcare": {"mohfw","aiims","apollo","fortis","abha","ayushman bharat"},
    "Water & Environment": {"jal shakti","cpcb"},
    "Financial Market Infra": {"nse","bse","nsdl","cdsl"}
}

def _kw_weight(sector: str, kw: str) -> float:
    """
    Heuristic weights:
      - Strong hints: 3.0
      - Multi-word operator/org names: 2.0
      - Generic tokens: 1.0
    """
    k = kw.lower()
    if k in _STRONG_HINTS.get(sector, set()):
        return 3.0
    if " " in k and len(k) >= 6:
        return 2.0
    return 1.0

def sector_raw_scores(text: str) -> dict:
    """Sum weighted keyword hits per sector (raw unnormalized score)."""
    t = text.lower()
    scores = {}
    for sector, kws in CII_SECTOR_KEYWORDS.items():
        s = 0.0
        for kw in kws:
            if kw in t:
                s += _kw_weight(sector, kw)
        scores[sector] = s
    return scores

def _normalize_score(raw: float, k: float = 6.0) -> float:
    """
    Soft saturation mapping raw→[0,1]:
        conf = raw / (raw + k)
    k controls how fast it saturates (6 works well for these dictionaries).
    """
    if raw <= 0:
        return 0.0
    return raw / (raw + k)

def sector_scores(text: str) -> dict:
    """Return sector→confidence (0..1) for all sectors."""
    raw = sector_raw_scores(text)
    return {sec: _normalize_score(v) for sec, v in raw.items()}

def tag_sector_with_confidence(text: str) -> tuple[str, float]:
    """Return (best_sector, best_confidence)."""
    confs = sector_scores(text)
    if not confs:
        return ("Other", 0.0)
    best_sector = max(confs, key=confs.get)
    best_conf = confs[best_sector]
    return (best_sector if best_conf > 0 else "Other", float(best_conf))



'''def tag_sector(text: str) -> str:
    t = text.lower()
    best, best_hits = None, 0
    for sector, kws in CII_SECTOR_KEYWORDS.items():
        hits = sum(1 for kw in kws if kw in t)
        if hits > best_hits:
            best, best_hits = sector, hits
    return best or "Other"'''

def tag_sector(text: str) -> str:
    t = text.lower()
    best, best_score = None, 0
    for sector, kws in CII_SECTOR_KEYWORDS.items():
        score = sum(2 for kw in kws if kw in t)  # weight per match
        if score > best_score:
            best, best_score = sector, score
    return best or "Other"

#Sector and Severity module
INDIA_ONLY = True          # set False if you want to keep everything but tag India
INDIA_MIN_SCORE = 0.25     # tune this; 0.2–0.3 works well for demo

def process_records(conn, records):
    saved = 0
    for rec in records:
        url, title, body = rec["url"], rec.get("title",""), rec.get("body","")
        text = clean_text(title, body)
        if len(text) < 120:
            continue

        content_sha = sha256(text)
        if get_seen_sha(conn, url) == content_sha:
            continue

        # ---- India + CTI relevance
        ind_score = india_relevance_score(text)
        rel = relevance_score(text)

        if INDIA_ONLY and ind_score < INDIA_MIN_SCORE:
            # skip non-India items if filter is ON
            continue

        # ---- Sector tag + ML attack probability
        sector = tag_sector(text)
        sector, sector_conf = tag_sector_with_confidence(text)
        iocs = extract_iocs(text)
        iocs["_meta"] = {"sector": sector, "sector_conf": float(sector_conf)}

        aprob = attack_probability(text, iocs)
        label = int(aprob >= ATTACK_THRESHOLD)

        # NEW LOGIC: Only predict attack type if label is 1
        attack_type = "Other"
        if label == 1:
            attack_type = predict_attack_type(text)

        rid = sha256((url or "") + "|" + (title or ""))
        upsert_incident(conn, rid, {
            "ts": rec.get("published") or datetime.utcnow().isoformat(),
            "source": rec.get("source",""),
            "url": url,
            "title": title,
            "text": text,
            "relevance_score": float(0.5*rel + 0.5*min(1.0, rel + ind_score*0.5)),  # combine with India boost
            "attack_prob": aprob,
            "attack_label": label,
            "iocs": iocs,
            "domain": domain_from(url)
        })
        upsert_seen(conn, url, content_sha)
        saved += 1
    return saved


def expand_frontier_from_seed(conn, seed_url, per_seed=25):
    r = http_get(seed_url)
    if not r: return 0
    links = extract_links(seed_url, r.text, max_links=per_seed)
    for link in links:
        push_frontier(conn, link, domain_from(link), priority=0.1)
    return len(links)

def run_cycle(conn):
    total_collected, total_saved = 0, 0

    # 1) RSS pass
    rss_items = []
    for feed in RSS_FEEDS:
        rss_items.extend(poll_rss(feed))
    total_collected += len(rss_items)
    total_saved += process_records(conn, rss_items)

    # 2) Frontier pass (HTML)
    batch = pick_urls(conn, n=100)
    for url, d in batch:
        art = fetch_article(url)
        delete_from_frontier(conn, url)

        if len((art.get("title","") + " " + art.get("body","")).strip()) < 120:
            update_domain_reward(conn, d, reward=0.0)
            continue

        title, body = art.get("title",""), art.get("body","")
        text = clean_text(title, body)
        ind_score = india_relevance_score(text)
        if INDIA_ONLY and ind_score < INDIA_MIN_SCORE:
            update_domain_reward(conn, d, reward=0.0)
            continue

        sector = tag_sector(text)
        rel = relevance_score(text)
        sector, sector_conf = tag_sector_with_confidence(text)
        iocs = extract_iocs(text)
        iocs["_meta"] = {"sector": sector, "sector_conf": float(sector_conf)}

        aprob = attack_probability(text, iocs)
        label = int(aprob >= ATTACK_THRESHOLD)

        # NEW LOGIC: Only predict attack type if label is 1
        attack_type = "Other"
        if label == 1:
            attack_type = predict_attack_type(text)


        rid = sha256((url or "") + "|" + (title or ""))
        content_sha = sha256(text)
        seen = get_seen_sha(conn, url)
        if (not seen) or (seen != content_sha):
            upsert_incident(conn, rid, {
                "ts": art.get("published") or datetime.utcnow().isoformat(),
                "source": "html",
                "url": url,
                "title": title,
                "text": text,
                "relevance_score": rel,
                "attack_prob": aprob,
                "attack_label": label,
                "attack_type": attack_type,
                "iocs": iocs,
                "domain": d
            })
            upsert_seen(conn, url, content_sha)
            total_saved += 1
        total_collected += 1

        # reward + expansion
        reward = 1.0 if rel >= 0.8 else (0.5 if rel >= RELEVANCE_THRESHOLD else 0.0)
        update_domain_reward(conn, d, reward=reward)

        if rel >= RELEVANCE_THRESHOLD:
            resp = http_get(url)
            if resp:
                for l in extract_links(url, resp.text, max_links=20):
                    push_frontier(conn, l, domain_from(l), priority=compute_priority(rel))

    return total_collected, total_saved

#core pipeline
def run_loop(num_cycles=3):
    """
    num_cycles=3 for Colab demo.
    For continuous mode on a VM, set a high number or while True.
    """
    conn = get_conn(DB_PATH)
    init_db(conn)

    # Seed frontier with HTML_SEEDS
    prepare_seed_frontier(conn, HTML_SEEDS)
    for seed in HTML_SEEDS:
        expand_frontier_from_seed(conn, seed, per_seed=25)

    for i in range(num_cycles):
        try:
            tot, saved = run_cycle(conn)
            print(f"[{datetime.utcnow().isoformat()}] Cycle {i+1}: Collected={tot} | Saved={saved}")
        except Exception as e:
            print("Cycle error:", e)
        if i < num_cycles - 1:
            time.sleep(SCHEDULE_SECONDS)

# On/Off switch
SCHEDULE_SECONDS = 90   # 1.5 min between cycles
run_loop(num_cycles=8)  # run 2 cycles now

import pandas as pd
conn = get_conn("/content/cti_realtime.sqlite")
df = pd.read_sql_query("""
SELECT ts, source, relevance_score, attack_prob, attack_label, attack_type, title, url
FROM incidents ORDER BY ts DESC LIMIT 100
""", conn)
df

#verification cell
import json, pandas as pd, sqlite3
conn = sqlite3.connect(DB_PATH)

df = pd.read_sql_query("SELECT title, iocs_json FROM incidents ORDER BY ts DESC LIMIT 100", conn)
df["_meta"] = df["iocs_json"].apply(lambda s: json.loads(s).get("_meta", {}))
df["sector"] = df["_meta"].apply(lambda m: m.get("sector"))
df["sector_conf"] = df["_meta"].apply(lambda m: m.get("sector_conf"))
df[["sector","sector_conf","title"]]

import sqlite3
import pandas as pd

DB_PATH = "/content/cti_realtime.sqlite"          # change this if needed
CSV_PATH = "data/incidents_latest.csv"       

# Export DB → CSV
conn = sqlite3.connect(DB_PATH)
df = pd.read_sql_query("""
SELECT ts, source, domain, relevance_score, attack_prob,
       attack_label,attack_type, title, url, iocs_json
FROM incidents
ORDER BY ts DESC
""", conn)
conn.close()

df.to_csv(CSV_PATH, index=False)
print("✅ CSV exported to Google Drive:", CSV_PATH)

df.head()

#NEW HTML 2x2

import pandas as pd
import json
import re
from datetime import date
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")

# --- Configuration ---
# Point this to the CSV file created by Cell 17
CSV_PATH = "data/incidents_latest.csv"
# This is the final dashboard file that will be created
OUT_HTML = "/content/cti_dashboard_2x2.html"

print(f"Loading data from: {CSV_PATH}")
try:
    df = pd.read_csv(CSV_PATH)
except FileNotFoundError:
    print(f"ERROR: Could not find '{CSV_PATH}'.")
    print("Please run the main crawler (Cell 17) to create the CSV file first.")
    # Create an empty DataFrame to avoid crashing the script
    df = pd.DataFrame(columns=["ts", "sector", "sector_conf", "attack_prob", "title", "url", "domain", "iocs_json"])

print(f"Loaded {len(df)} records.")

# --- Normalize timestamp ---
ts_cols = [c for c in ["ts","timestamp","date","datetime","created_at"] if c in df.columns]
if ts_cols:
    df["ts"] = pd.to_datetime(df[ts_cols[0]], errors="coerce", utc=True)
else:
    df["ts"] = pd.NaT

df["date"] = df["ts"].dt.date.astype("string").fillna("")

# --- Ensure required columns exist ---
for col, default in [
    ("sector",""),
    ("sector_conf",0.0),
    ("attack_prob",0.0),
    ("title",""),
    ("domain",""),
    ("url",""),
    ("iocs_json","{}")
]:
    if col not in df.columns:
        df[col] = default

df["attack_prob"] = pd.to_numeric(df["attack_prob"], errors="coerce").fillna(0.0)
df["sector_conf"] = pd.to_numeric(df["sector_conf"], errors="coerce").fillna(0.0)

# Extract from iocs_json if sector missing
def meta_sector(v):
    try:
        # Check if v is already a dict (from JSON) or a string
        if isinstance(v, str):
            data = json.loads(v)
        elif isinstance(v, dict):
            data = v
        else:
            return ""
        return data.get("_meta", {}).get("sector", "")
    except:
        return ""

df.loc[(df["sector"]=="")|(df["sector"].isna()), "sector"] = df["iocs_json"].apply(meta_sector)

# --- Sector inference rules ---
print("Inferring missing sectors...")
SECTOR_KWS = {
    "Banking/Finance": [r"upi", r"npci", r"aadhaar", r"sbi", r"hdfc", r"icici", r"rbi", r"imps", r"sebi", r"nbfc", r"fintech"],
    "Telecom": [r"airtel", r"jio", r"vi ", r"bsnl", r"5g", r"telecom", r"isp"],
    "Government/PSU": [r"gov\.in", r"nic\.in", r"cert-in", r"nciipc", r"meity", r"psu", r"ministry"],
    "Defence/Space": [r"isro", r"drdo", r"army", r"navy", r"air force", r"mod\.in"],
    "Transport": [r"railway", r"metro", r"airport", r"aai", r"irctc", r"nhai"],
    "Oil/Gas": [r"ongc", r"iocl", r"hpcl", r"bpcl", r"gail", r"oil india", r"refinery"],
    "Power/Energy": [r"ntpc", r"power grid", r"substation", r"discom", r"energy"],
    "Healthcare": [r"hospital", r"aiims", r"covid", r"mohfw", r"icmr", r"pharma"],
    "IT & Tech": [r"cloud", r"azure", r"aws", r"datacenter", r"saas"]
}

def infer_sector(row):
    text = (str(row["title"])+" "+str(row["domain"])).lower()
    best, hits = "Other", 0
    for sector, keys in SECTOR_KWS.items():
        count = sum(1 for pat in keys if re.search(pat, text))
        if count > hits:
            best, hits = sector, count
    # Return confidence as a simple ratio
    return best, min(1.0, hits/3) # 3 hits = 100% confidence

empty_mask = df["sector"].eq("") | df["sector"].str.lower().eq("other")
df.loc[empty_mask, ["sector","sector_conf"]] = df.loc[empty_mask].apply(
    lambda r: infer_sector(r), axis=1, result_type="expand"
)

# Convert final data records
print("Preparing final data for dashboard...")
data = df[["ts","date","sector","sector_conf","attack_prob","title","url","domain"]].copy()
data["ts"] = pd.to_datetime(data["ts"], errors="coerce", utc=True).dt.strftime("%Y-%m-%d %H:%M:%S").fillna("")
records = data.to_dict(orient="records")

DMIN = min(d for d in df["date"] if d) if len(df) and df["date"].str.len().max() > 0 else date.today().strftime('%Y-%m-01')
DMAX = max(d for d in df["date"] if d) if len(df) and df["date"].str.len().max() > 0 else date.today().strftime('%Y-%m-%d')

# === HTML Template (ALL { } escaped as {{ }}) ===
html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>CTI Dashboard - India CII</title>
<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; padding: 0; background-color: #f8f9fa; color: #212529; }}
  .header {{ background-color: #343a40; color: white; padding: 20px 40px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  .header h2 {{ margin: 0; }}
  .container {{ padding: 20px 40px; }}
  .row {{ display:flex; gap:20px; flex-wrap:wrap; margin-bottom: 20px; }}
  .card {{ background:white; padding: 20px; border-radius:8px; flex:1 1 300px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); border: 1px solid #dee2e6; }}
  .card-filter {{ flex-grow: 1; flex-basis: 320px; max-width: 400px; }}
  .card-chart {{ flex-grow: 2; flex-basis: 400px; min-width: 400px; }}
  .pill {{ background:#e9ecef; color: #495057; padding: 6px 12px; border-radius:16px; margin:4px; font-size:12px; display: inline-block; }}
  .filter-box {{ max-height: 200px; overflow-y: auto; border: 1px solid #ced4da; padding: 10px; border-radius: 4px; background: #fdfdfd; }}
  .filter-box label {{ display: block; margin-bottom: 5px; font-size: 14px; }}
  input[type="range"] {{ width: 100%; }}
  input[type="text"], input[type="date"] {{ width: 95%; padding: 8px; font-size: 14px; border: 1px solid #ced4da; border-radius: 4px; margin-bottom: 10px; }}
  button {{ background-color: #007bff; color: white; border: none; padding: 10px 15px; border-radius: 4px; cursor: pointer; font-size: 14px; margin-right: 5px; }}
  button:hover {{ background-color: #0056b3; }}
  button.reset {{ background-color: #6c757d; }}
  button.reset:hover {{ background-color: #5a6268; }}
</style>
</head>
<body>

<div class="header">
  <h2>🇮🇳 India CII — Cyber Incidents Dashboard</h2>
</div>

<div class="container">
  <div>
    <span id="loaded" class="pill"></span>
    <span id="filtered" class="pill"></span>
  </div>

  <div class="row">
    <div class="card card-filter">
      <strong>Filters</strong><br><br>
      <div id="sectorBox" class="filter-box"></div><br>

      Min Attack Prob: <input type="range" id="minP" min="0" max="1" step="0.01" value="0"> <span id="minPV">0.00</span><br>
      Min Sector Conf: <input type="range" id="minC" min="0" max="1" step="0.01" value="0"> <span id="minCV">0.00</span><br><br>
      Search Title: <input id="search" style="width:100%" placeholder="e.g., ransomware, bank"><br><br>

      <label><input type="checkbox" id="useDate"> Enable Date Filter</label><br>
      <div id="dateDiv" style="display:none; padding-top: 10px;">
        Start: <input type="date" id="sd" value="{DMIN}"><br>
        End: &nbsp; <input type="date" id="ed" value="{DMAX}">
      </div>
      <br>
      <button onclick="apply()">Apply</button>
      <button onclick="resetF()" class="reset">Reset</button>
    </div>

    <div class="card card-chart"><div id="chart1" style="height: 400px;"></div></div>
    <div class="card card-chart"><div id="chart2" style="height: 400px;"></div></div>
  </div>

  <div class="row">
    <div class="card card-chart"><div id="chart3" style="height: 500px;"></div></div>
    <div class="card card-chart"><div id="chart4" style="height: 500px;"></div></div>
  </div>
</div>

<script>
const ALL = {json.dumps(records)};
let VIEW = [...ALL];
let SECTORS = [...new Set(ALL.map(r => r.sector || "Other"))].sort();
let SEL = new Set(SECTORS);

document.getElementById("loaded").innerHTML = "Loaded: " + ALL.length;

// --- Range slider value display ---
document.getElementById("minP").oninput = (e) =>
  document.getElementById("minPV").innerHTML = parseFloat(e.target.value).toFixed(2);
document.getElementById("minC").oninput = (e) =>
  document.getElementById("minCV").innerHTML = parseFloat(e.target.value).toFixed(2);

function renderSectors() {{
  let box = document.getElementById("sectorBox");
  box.innerHTML = "";
  SECTORS.forEach(s => {{
    let id = "s_" + s.replace(/[^a-z0-9]/gi,"_");
    box.innerHTML += `<label><input type='checkbox' id='${{id}}' ${{(SEL.has(s) ? "checked" : "")}}> ${{s}}</label>`;
  }});
  // Add event listeners *after* innerHTML is set
  SECTORS.forEach(s => {{
    let id = "s_" + s.replace(/[^a-z0-9]/gi,"_");
    document.getElementById(id).onchange = e => {{
      if(e.target.checked) SEL.add(s);
      else SEL.delete(s);
    }};
  }});
}}

function resetF() {{
  SEL = new Set(SECTORS);
  renderSectors();
  document.getElementById("minP").value = 0;
  document.getElementById("minC").value = 0;
  document.getElementById("minPV").innerHTML = "0.00";
  document.getElementById("minCV").innerHTML = "0.00";
  document.getElementById("search").value = "";
  document.getElementById("useDate").checked = false;
  document.getElementById("dateDiv").style.display = "none";
  document.getElementById("sd").value = "{DMIN}";
  document.getElementById("ed").value = "{DMAX}";
  apply();
}}

document.getElementById("useDate").onchange = () =>
  document.getElementById("dateDiv").style.display =
    document.getElementById("useDate").checked ? "block" : "none";

function apply() {{
  let mp = parseFloat(document.getElementById("minP").value);
  let mc = parseFloat(document.getElementById("minC").value);
  let q = document.getElementById("search").value.toLowerCase();
  let dateE = document.getElementById("useDate").checked;
  let sd = document.getElementById("sd").value;
  let ed = document.getElementById("ed").value;

  VIEW = ALL.filter(r => {{
    if(!SEL.has(r.sector)) return false;
    if(r.attack_prob < mp) return false;
    if(r.sector_conf < mc) return false;
    if(q && !r.title.toLowerCase().includes(q)) return false;
    if(dateE && r.date && (r.date < sd || r.date > ed)) return false;
    return true;
  }});

  document.getElementById("filtered").innerHTML = "Filtered: " + VIEW.length;
  charts();
}}

// --- MODIFIED CHARTS FUNCTION ---
function charts() {{

  // --- CHART 1 (Count by Sector) ---
  let count = {{}};
  VIEW.forEach(r => count[r.sector] = (count[r.sector]||0)+1);
  let sortedSectors = Object.keys(count).sort((a,b) => count[b] - count[a]);
  let sortedCounts = sortedSectors.map(s => count[s]);

  Plotly.newPlot("chart1", [{{
    x: sortedCounts,
    y: sortedSectors,
    type: "bar",
    orientation: "h"
  }}], {{
    title: "Incidents by Sector (Volume)", // Title tweaked
    margin: {{ l: 120, t: 40, b: 40, r: 20 }},
    yaxis: {{ autorange: "reversed" }}
  }}, {{responsive: true}});

  // --- Aggregation for Charts 2 & 4 ---
  let sum={{}}, cnt={{}};
  VIEW.forEach(r => {{
    sum[r.sector] = (sum[r.sector]||0)+r.attack_prob;
    cnt[r.sector] = (cnt[r.sector]||0)+1;
  }});
  let sectors = Object.keys(sum).filter(k => cnt[k] > 0);
  let avg = sectors.map(k => sum[k]/cnt[k]);
  let counts = sectors.map(k => cnt[k]); // Get counts

  // --- CHART 2 (Avg Attack Prob) ---
  let sortedData2 = sectors.map((s, i) => ({{sector: s, avg: avg[i]}}))
      .sort((a,b) => b.avg - a.avg);

  Plotly.newPlot("chart2", [{{
    x: sortedData2.map(d => d.avg),
    y: sortedData2.map(d => d.sector),
    type: "bar",
    orientation: "h"
  }}], {{
    title: "Avg Attack Probability by Sector (Severity)", // Title tweaked
    yaxis:{{ autorange: "reversed" }},
    xaxis:{{range:[0,1]}},
    margin: {{ l: 120, t: 40, b: 40, r: 20 }}
  }}, {{responsive: true}});

  // --- CHART 3 (Heatmap) ---
  let dm={{}};
  VIEW.forEach(r => {{
    let k=r.date+"_"+r.sector;
    if(!dm[k]) dm[k]={{sum:0,c:0}};
    dm[k].sum+=r.attack_prob;
    dm[k].c++;
  }});
  let sectors2=[...new Set(VIEW.map(r=>r.sector))].sort();
  let dates=[...new Set(VIEW.map(r=>r.date))].sort();
  let H=[];
  sectors2.forEach(s => {{
    let row=[]; dates.forEach(d => {{
      let k=d+"_"+s; let o=dm[k];
      row.push(o?o.sum/o.c:0);
    }});
    H.push(row);
  }});
  Plotly.newPlot("chart3", [{{
    x: dates,
    y: sectors2,
    z: H,
    type: "heatmap",
    colorscale: "Reds",
    showscale: false
  }}], {{
    title:"Date × Sector Heatmap (Avg Attack Prob)",
    margin: {{ l: 120, t: 60, b: 60, r: 20 }}
  }}, {{responsive: true}});

  // --- NEW CHART 4 (Bubble Plot) ---
  let bubbleData = sectors.map((s, i) => ({{
      sector: s,
      avg: avg[i],
      count: counts[i]
  }}));

  // Get max count for scaling bubble size
  let maxCount = Math.max(...bubbleData.map(d => d.count));
  let sizeRef = maxCount > 0 ? 2.0 * maxCount / (40**2) : 1; // 40px max radius

  Plotly.newPlot("chart4", [{{
      x: bubbleData.map(d => d.sector),
      y: bubbleData.map(d => d.avg),
      mode: 'markers',
      marker: {{
          size: bubbleData.map(d => d.count),
          sizeref: sizeRef,
          sizemin: 4,
          color: bubbleData.map(d => d.avg), // Color by severity
          colorscale: 'YlOrRd', // Yellow-Orange-Red scale
          showscale: true,
          colorbar: {{ title: 'Avg<br>Severity' }}
      }},
      text: bubbleData.map(d => `<b>${{d.sector}}</b><br>Avg Severity: ${{d.avg.toFixed(2)}}<br>Count: ${{d.count}}`),
      hoverinfo: 'text',
      type: 'scatter'
  }}], {{
      title: "Sector Severity (Y-Axis) vs. Volume (Size)",
      yaxis: {{ title: 'Average Severity (Attack Prob)', range: [0, 1.05] }},
      xaxis: {{ title: 'Sector', automargin: true }},
      margin: {{ l: 80, t: 60, b: 120, r: 20 }} // More bottom margin for sector labels
  }}, {{responsive: true}});
}}

renderSectors();
charts();
</script>
</body>
</html>
"""

# Write the final HTML file to Colab's local storage
with open(OUT_HTML,"w",encoding="utf-8") as f:
    f.write(html)

print(f"\n✅ HTML Dashboard updated: {OUT_HTML}")
print("You can now download this file from the Colab file browser (folder icon) and open it.")